### ISSUE TITLE
Resume Kier Lindsay

### ISSUE THREAD

**Issue by veragreen119** [lorrnel/SFU_CMPT276_2019#3]
Please provide an updated copy of your resume listing your computer science specialization orientation and any relevant courses. 

**For reference:**
Kier is a third year computer science student at Simon Fraser University.  Kier has a passion for Linux and all things open source.  Kier's background in technical sales and home security system installation combined with his passion for computer technology brings a lot to the table in terms of motivation and technical know-how.
Kier's personal experience includes virtual server deployment, server administration, server community moderation, simple application development, and hardware/software integration including raspberry pi, and arduino.  Kier also has a passion for drones and has constructed and piloted his own drones for 5 years.  In terms of programming , Kier is familiar with multiple programming languages and programming  concepts including multi-threading, visual recognition, and machine learning.

**Catch Phrases:**
visual recognition, machine learning, AI, hardware/software interfacing.

**Comment by syonfox** [comment]
[20191003_KierResume_Tech.pdf](https://github.com/lorrnel/SFU_CMPT276_2019/files/3688502/20191003_KierResume_Tech.pdf)

[20191003_KierResume_Tech.docx](https://github.com/lorrnel/SFU_CMPT276_2019/files/3688504/20191003_KierResume_Tech.docx)
